version: "3"
services:
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: development
    environment:
      - NODE_ENV=development
    command: npm run dev
    networks:
      - paragon_net
    volumes:
      - ./:/app:ro
      - /app/node_modules
  

  db:
    container_name: paragon_db
    image: mysql:8.0
    command: 
      --default-authentication-plugin=mysql_native_password
      --init-file ./src/data/db_init.sql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: paragon
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: paragon99
      SERVICE_TAG: dev
      SERVICE_NAME: paragon_db
    networks:
      - paragon_net
    volumes:
      - ./src/data/db_init.sql:/docker-entrypoint-initdb.d/
      - mysql-data:/var/lib/mysql

    
    
  phpmyadmin:
    container_name: sql_admin
    image: phpmyadmin:5.2.0-apache
    restart: always
    networks:
      - paragon_net
    depends_on:
      - db  
  
  nginx:
    container_name: nginx
    image: nginx:1.22-alpine
    ports:
      - 80:80
      # - 443:443
    networks:
      - paragon_net
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
networks:
  paragon_net:
   driver: bridge